/* default config file for libdigidoc */
#define SYSCONFDIR "@CMAKE_INSTALL_FULL_SYSCONFDIR@"

/* Version number of package */
#define VERSION "@VERSION@"
#define DIGIDOC_VERSION "@VERSION@"
#define VERSION_COMMA @PROJECT_VERSION_MAJOR@,@PROJECT_VERSION_MINOR@,@PROJECT_VERSION_PATCH@,@BUILD_VER@
