#--------------------------------------------------
# @DIGIDOC_CONF_NAME@
# DigiDoc library global configuration file
#--------------------------------------------------

[ca]
CA_CERT_PATH=@CMAKE_INSTALL_FULL_DATADIR@/libdigidoc
CA_CERTS=17

CA_CERT_1=JUUR-SK.crt
CA_CERT_1_CN=Juur-SK
CA_CERT_2=ESTEID-SK.crt
CA_CERT_2_CN=ESTEID-SK
CA_CERT_3=ESTEID-SK 2007.crt
CA_CERT_3_CN=ESTEID-SK 2007
CA_CERT_4=KLASS3-SK.crt
CA_CERT_4_CN=KLASS3-SK
CA_CERT_5=KLASS3-SK 2010.crt
CA_CERT_5_CN=KLASS3-SK 2010
CA_CERT_6=KLASS3-SK 2010 EECCRCA.crt
CA_CERT_6_CN=KLASS3-SK 2010
CA_CERT_7=EID-SK.crt
CA_CERT_7_CN=EID-SK
CA_CERT_8=EID-SK 2007.crt
CA_CERT_8_CN=EID-SK 2007

CA_CERT_9=EECCRCA.crt
CA_CERT_9_CN=EE Certification Centre Root CA
CA_CERT_10=ESTEID-SK 2011.crt
CA_CERT_10_CN=ESTEID-SK 2011
CA_CERT_11=EID-SK 2011.crt
CA_CERT_11_CN=EID-SK 2011

CA_CERT_12=TEST Juur-SK.crt
CA_CERT_12_CN=TEST Juur-SK
CA_CERT_13=TEST-SK.crt
CA_CERT_13_CN=TEST-SK

CA_CERT_14=TEST EECCRCA.crt
CA_CERT_14_CN=TEST of EE Certification Centre Root CA
CA_CERT_15=TEST ESTEID-SK 2011.crt
CA_CERT_15_CN=TEST of ESTEID-SK 2011
CA_CERT_16=TEST EID-SK 2011.crt
CA_CERT_16_CN=TEST of EID-SK 2011
CA_CERT_17=TEST KLASS3 2010.crt
CA_CERT_17_CN=TEST of KLASS3-SK 2010




DIGIDOC_DEFAULT_DRIVER=1
DIGIDOC_DRIVERS=1
DIGIDOC_DRIVER_1_NAME=OpenSC
DIGIDOC_DRIVER_1_DESC=OpenSC projects PKCS#11 driver
DIGIDOC_DRIVER_1_FILE=@PKCS11_MODULE@
DIGIDOC_SIGNATURE_SLOT=1
CHECK_OCSP_NONCE=0

SIGN_OCSP=0
USE_PROXY=0
DIGIDOC_OCSP_URL=http://ocsp.sk.ee

DIGIDOC_OCSP_RESPONDER_CERTS=24

DIGIDOC_OCSP_RESPONDER_CERT_1=TEST-SK OCSP 2005.crt
DIGIDOC_OCSP_RESPONDER_CERT_1_CN=TEST-SK OCSP RESPONDER 2005
DIGIDOC_OCSP_RESPONDER_CERT_1_CA=TEST-SK
DIGIDOC_OCSP_RESPONDER_CERT_1_URL=http://www.openxades.org/cgi-bin/ocsp.cgi

DIGIDOC_OCSP_RESPONDER_CERT_2=KLASS3-SK OCSP 2009.crt
DIGIDOC_OCSP_RESPONDER_CERT_2_CN=KLASS3-SK OCSP RESPONDER 2009
DIGIDOC_OCSP_RESPONDER_CERT_2_CA=KLASS3-SK

DIGIDOC_OCSP_RESPONDER_CERT_3=ESTEID-SK OCSP 2005.crt
DIGIDOC_OCSP_RESPONDER_CERT_3_CN=ESTEID-SK OCSP RESPONDER 2005
DIGIDOC_OCSP_RESPONDER_CERT_3_CA=ESTEID-SK

DIGIDOC_OCSP_RESPONDER_CERT_4=ESTEID-SK 2007 OCSP.crt
DIGIDOC_OCSP_RESPONDER_CERT_4_CN=ESTEID-SK 2007 OCSP RESPONDER
DIGIDOC_OCSP_RESPONDER_CERT_4_CA=ESTEID-SK 2007

DIGIDOC_OCSP_RESPONDER_CERT_5=EID-SK 2007 OCSP.crt
DIGIDOC_OCSP_RESPONDER_CERT_5_CN=EID-SK 2007 OCSP RESPONDER
DIGIDOC_OCSP_RESPONDER_CERT_5_CA=EID-SK 2007

DIGIDOC_OCSP_RESPONDER_CERT_6=EID-SK OCSP 2006.crt
DIGIDOC_OCSP_RESPONDER_CERT_6_1=EID-SK OCSP.crt
DIGIDOC_OCSP_RESPONDER_CERT_6_CN=EID-SK OCSP RESPONDER
DIGIDOC_OCSP_RESPONDER_CERT_6_CA=EID-SK

DIGIDOC_OCSP_RESPONDER_CERT_7=ESTEID-SK OCSP.crt
DIGIDOC_OCSP_RESPONDER_CERT_7_CN=ESTEID-SK OCSP RESPONDER
DIGIDOC_OCSP_RESPONDER_CERT_7_CA=ESTEID-SK

DIGIDOC_OCSP_RESPONDER_CERT_8=KLASS3-SK OCSP 2006.crt
DIGIDOC_OCSP_RESPONDER_CERT_8_1=KLASS3-SK OCSP.crt
DIGIDOC_OCSP_RESPONDER_CERT_8_CN=KLASS3-SK OCSP RESPONDER
DIGIDOC_OCSP_RESPONDER_CERT_8_CA=KLASS3-SK

DIGIDOC_OCSP_RESPONDER_CERT_9=EID-SK 2007 OCSP 2010.crt
DIGIDOC_OCSP_RESPONDER_CERT_9_CN=EID-SK 2007 OCSP RESPONDER 2010
DIGIDOC_OCSP_RESPONDER_CERT_9_CA=EID-SK 2007

DIGIDOC_OCSP_RESPONDER_CERT_10=ESTEID-SK 2007 OCSP 2010.crt
DIGIDOC_OCSP_RESPONDER_CERT_10_CN=ESTEID-SK 2007 OCSP RESPONDER 2010
DIGIDOC_OCSP_RESPONDER_CERT_10_CA=ESTEID-SK 2007

DIGIDOC_OCSP_RESPONDER_CERT_11=KLASS3-SK 2010 OCSP.crt
DIGIDOC_OCSP_RESPONDER_CERT_11_CN=KLASS3-SK 2010 OCSP RESPONDER
DIGIDOC_OCSP_RESPONDER_CERT_11_CA=KLASS3-SK 2010

DIGIDOC_OCSP_RESPONDER_CERT_12=SK OCSP 2011.crt
DIGIDOC_OCSP_RESPONDER_CERT_12_CN=SK OCSP RESPONDER 2011
DIGIDOC_OCSP_RESPONDER_CERT_12_CA=EE Certification Centre Root CA

DIGIDOC_OCSP_RESPONDER_CERT_13=SK OCSP 2011.crt
DIGIDOC_OCSP_RESPONDER_CERT_13_CN=SK OCSP RESPONDER 2011
DIGIDOC_OCSP_RESPONDER_CERT_13_CA=ESTEID-SK 2011

DIGIDOC_OCSP_RESPONDER_CERT_14=SK OCSP 2011.crt
DIGIDOC_OCSP_RESPONDER_CERT_14_CN=SK OCSP RESPONDER 2011
DIGIDOC_OCSP_RESPONDER_CERT_14_CA=EID-SK 2011

DIGIDOC_OCSP_RESPONDER_CERT_15=TEST SK OCSP 2011.crt
DIGIDOC_OCSP_RESPONDER_CERT_15_CN=TEST of SK OCSP RESPONDER 2011
DIGIDOC_OCSP_RESPONDER_CERT_15_CA=TEST of EE Certification Centre Root CA
DIGIDOC_OCSP_RESPONDER_CERT_15_URL=http://www.openxades.org/cgi-bin/ocsp.cgi

DIGIDOC_OCSP_RESPONDER_CERT_16=TEST SK OCSP 2011.crt
DIGIDOC_OCSP_RESPONDER_CERT_16_CN=TEST of SK OCSP RESPONDER 2011
DIGIDOC_OCSP_RESPONDER_CERT_16_CA=TEST of ESTEID-SK 2011
DIGIDOC_OCSP_RESPONDER_CERT_16_URL=http://www.openxades.org/cgi-bin/ocsp.cgi

DIGIDOC_OCSP_RESPONDER_CERT_17=TEST SK OCSP 2011.crt
DIGIDOC_OCSP_RESPONDER_CERT_17_CN=TEST of SK OCSP RESPONDER 2011
DIGIDOC_OCSP_RESPONDER_CERT_17_CA=TEST of EID-SK 2011
DIGIDOC_OCSP_RESPONDER_CERT_17_URL=http://www.openxades.org/cgi-bin/ocsp.cgi

DIGIDOC_OCSP_RESPONDER_CERT_18=TEST SK OCSP 2011.crt
DIGIDOC_OCSP_RESPONDER_CERT_18_CN=TEST of SK OCSP RESPONDER 2011
DIGIDOC_OCSP_RESPONDER_CERT_18_CA=TEST of KLASS3-SK 2010
DIGIDOC_OCSP_RESPONDER_CERT_18_URL=http://www.openxades.org/cgi-bin/ocsp.cgi

DIGIDOC_OCSP_RESPONDER_CERT_19=TEST SK OCSP 2011.crt
DIGIDOC_OCSP_RESPONDER_CERT_19_CN=TEST of SK OCSP RESPONDER 2011
DIGIDOC_OCSP_RESPONDER_CERT_19_CA=VRK CA for Test Purposes
DIGIDOC_OCSP_RESPONDER_CERT_19_URL=http://www.openxades.org/cgi-bin/ocsp.cgi

DIGIDOC_OCSP_RESPONDER_CERT_20=TEST SK OCSP 2011.crt
DIGIDOC_OCSP_RESPONDER_CERT_20_CN=TEST of SK OCSP RESPONDER 2011
DIGIDOC_OCSP_RESPONDER_CERT_20_CA=VRK TEST Root CA
DIGIDOC_OCSP_RESPONDER_CERT_20_URL=http://www.openxades.org/cgi-bin/ocsp.cgi

DIGIDOC_OCSP_RESPONDER_CERT_21=SK OCSP 2011.crt
DIGIDOC_OCSP_RESPONDER_CERT_21_CN=SK OCSP RESPONDER 2011
DIGIDOC_OCSP_RESPONDER_CERT_21_CA=VRK Gov. Root CA
DIGIDOC_OCSP_RESPONDER_CERT_21_URL=http://ocsp.sk.ee/_proxy

DIGIDOC_OCSP_RESPONDER_CERT_22=SK OCSP 2011.crt
DIGIDOC_OCSP_RESPONDER_CERT_22_CN=SK OCSP RESPONDER 2011
DIGIDOC_OCSP_RESPONDER_CERT_22_CA=VRK Gov. CA for Citizen Qualified Certificates
DIGIDOC_OCSP_RESPONDER_CERT_22_URL=http://ocsp.sk.ee/_proxy

DIGIDOC_OCSP_RESPONDER_CERT_23=SK OCSP 2011.crt
DIGIDOC_OCSP_RESPONDER_CERT_23_CN=SK OCSP RESPONDER 2011
DIGIDOC_OCSP_RESPONDER_CERT_23_CA=VRK CA for Healthcare Professionals Qualified Certificates
DIGIDOC_OCSP_RESPONDER_CERT_23_URL=http://ocsp.sk.ee/_proxy

DIGIDOC_OCSP_RESPONDER_CERT_24=SK OCSP 2011.crt
DIGIDOC_OCSP_RESPONDER_CERT_24_CN=SK OCSP RESPONDER 2011
DIGIDOC_OCSP_RESPONDER_CERT_24_CA=VRK CA for Qualified Certificates
DIGIDOC_OCSP_RESPONDER_CERT_24_URL=http://ocsp.sk.ee/_proxy
